package com.example.triage;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;

public class Patient implements Serializable {
	/**
	 * This class is designed for each individual patient object. Inside, we can
	 * store a patient's name, DOB, and health card number and a collection of
	 * his/her visit records. DataManager class can access the addVisit method
	 * in this class to add a new visit record.
	 */

	/** This UID was generated by Eclipse. */
	private static final long serialVersionUID = -3715852907273175917L;

	/** This Patient's unique id */
	private int patientId;

	/** This Patient's name. */
	private String[] name;

	/** This Patient's date of birth in format yyyy:MM:dd. */
	private Date dob;

	/** This Patient's age. */
	private int age;

	/** This Patient's health card number. */
	private String healthcard;

	/** A collection of Visits at different time. */
	private ArrayList<Visit> visitData;

	/**
	 * An empty constructor for a Patient.
	 */
	public Patient() {
	}

	/**
	 * Constructs a Patient with names from name and date of birth made up of
	 * day, month, and year and health card number from healthcard.
	 * 
	 * @param name
	 *            This Patient's name.
	 * @param day
	 *            This Patient's day of birth.
	 * @param month
	 *            This Patient's month of birth.
	 * @param year
	 *            This Patient's year of birth.
	 * @param healthcard
	 *            This Patient's health card number.
	 */
	public Patient(String[] name, int day, int month, int year,
			String healthcard) {
		this.setName(name);
		Calendar c = Calendar.getInstance();
		c.clear();
		c.set(year, month - 1, day);
		this.dob = c.getTime();
		this.setHealthcard(healthcard);
		this.setAge(this.dob);

	}

	/**
	 * Constructs a Patient with names from name and date of birth made up of
	 * day, month, and year and health card number from healthcard. Additionally
	 * with patientId.
	 * 
	 * @param patientId
	 *            This Patient's Id
	 * @param name
	 *            This Patient's name.
	 * @param day
	 *            This Patient's day of birth.
	 * @param month
	 *            This Patient's month of birth.
	 * @param year
	 *            This Patient's year of birth.
	 * @param healthcard
	 *            This Patient's health card number.
	 */
	public Patient(int patientId, String[] name, int day, int month, int year,
			String healthcard) {
		this.setPatientId(patientId);
		this.setName(name);
		Calendar c = Calendar.getInstance();
		c.clear();
		c.set(year, month - 1, day);
		this.dob = c.getTime();
		this.setHealthcard(healthcard);
		this.setAge(this.dob);

	}

	/**
	 * Returns this Patient's ID
	 * 
	 * @return The ID of this patient
	 */
	public int getPatientId() {
		return patientId;
	}

	/**
	 * Sets the ID of this Patient to patientId
	 * 
	 * @param patientId
	 *            The patientId of this Patient.
	 */
	public void setPatientId(int patientId) {
		this.patientId = patientId;
	}

	/**
	 * Returns this Patient's name.
	 * 
	 * @return The name of this Patient.
	 */
	public String[] getName() {
		return name;
	}

	/**
	 * Returns this Patient's full name
	 * 
	 * @return The name of this Patient
	 */
	public String getFullName() {
		return this.name[0] + " " + this.name[1];
	}

	/**
	 * Sets the name of this Patient to name.
	 * 
	 * @param name
	 *            The new name of this Patient.
	 */
	public void setName(String[] name) {
		this.name = name;
	}

	/**
	 * Returns this Patient's health card number.
	 * 
	 * @return The health card number of this Patient.
	 */
	public String getHealthcard() {
		return healthcard;
	}

	/**
	 * Sets the health card number of this Patient to healthcard.
	 * 
	 * @param healthcard
	 *            The new health card number of this Patient.
	 */
	public void setHealthcard(String healthcard) {
		this.healthcard = healthcard;
	}

	/**
	 * Returns this Patient's date of birth.
	 * 
	 * @return The date of birth of this Patient.
	 */
	public Date getDob() {
		return dob;
	}

	/**
	 * Sets the date of birth of this Patient to dob.
	 * 
	 * @param dob
	 *            The new date of birth of this Patient.
	 */
	public void setDob(Date dob) {
		this.dob = dob;
	}

	/**
	 * Returns this Patient's visit data.
	 * 
	 * @return The visit data of this Patient.
	 */
	public ArrayList<Visit> getVisitData() {
		return visitData;
	}

	/**
	 * Sets the visit data of this Patient to visitData.
	 * 
	 * @param visitData
	 *            The new visit data of this Patient.
	 */
	public void setVisitData(ArrayList<Visit> visitData) {
		this.visitData = visitData;
	}

	/**
	 * Returns this Patient's age.
	 * 
	 * @return The age of this Patient.
	 */
	public int getAge() {
		return age;
	}

	/**
	 * Sets the age of this Patient.
	 * 
	 * @param dob
	 *            The date of birth of this Patient.
	 */
	public void setAge(Date dob) {
		Calendar c = Calendar.getInstance();
		c.setTime(dob);
		Calendar Today = Calendar.getInstance();
		this.age = Today.get(Calendar.YEAR) - c.get(Calendar.YEAR);
		if (Today.get(Calendar.MONTH) < c.get(Calendar.MONTH)) {
			this.age--;
		} else if (Today.get(Calendar.MONTH) == c.get(Calendar.MONTH)
				&& Today.get(Calendar.DAY_OF_MONTH) < c
						.get(Calendar.DAY_OF_MONTH)) {
			this.age--;
		}
	}

	/**
	 * Returns SQL formatted date
	 * 
	 * @return SQL format date
	 */
	public String getSQLDate() {
		Calendar calendar = Calendar.getInstance();
		calendar.setTime(this.dob);
		int day = calendar.get(Calendar.DAY_OF_MONTH);
		int month = calendar.get(Calendar.MONTH) + 1;
		int year = calendar.get(Calendar.YEAR);

		return year + "-" + month + "-" + day;
	}

	/**
	 * Returns a string representation of this Patient.
	 * 
	 * @return A string representation of this Patient.
	 */
	public String toString() {
		Calendar calendar = Calendar.getInstance();
		calendar.setTime(this.dob);
		int day = calendar.get(Calendar.DAY_OF_MONTH);
		int month = calendar.get(Calendar.MONTH) + 1;
		int year = calendar.get(Calendar.YEAR);
		String patientName = "";
		for (String n : name) {
			patientName += n + " ";
		}
		return "[Name:" + patientName.trim() + ", Date Of Birth:" + day + "/"
				+ month + "/" + year + ", Health Card Number:"
				+ this.healthcard + "]";
	}

	/**
	 * Adds a new Visit of this Patient.
	 * 
	 * @param visitId
	 * @param patientId
	 * 
	 * @param arrivalTime
	 *            The arrival time of this Patient.
	 */
	public void addVisit(int visitId, int patientId, String arrivalTime) {

		Visit visit = new Visit(arrivalTime, visitId, patientId);

		if (visitData == null) {
			this.setVisitData(new ArrayList<Visit>());
		}

		this.visitData.add(visit);

	}

	/**
	 * Sets the age of this Patient
	 * 
	 * @param age This Patient's age
	 */
	public void setAge(int age) {
		this.age = age;
	}

}
